[package]
name = "{{ project-name }}"
version = "0.1.0"
edition = "2021"
description = "{{ description }}"
authors = [ "{{ authors }}" ]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yedmq-mqtt = "0.1.0"
yedmq-plugin = "0.1.0"
anyhow = "1.0"